version: '3'

services:
  frontend:
    #Dockerfile의 경로
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

      
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리(작업공간 app으로 설정해줌 -> frontend/Dockerfile)
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
    - .:/user/src/gz-salon


  db:
    image: mysql:8.0.29
    platform: Linux/AMD64
    ports:  
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    restart: always
    #호스트 ./data에 데이터를 저장시키고, ./conf를 통하여 mysql.conf를 공유
    
volumes : 
  mysql_data:


