version: '3'

services:
  frontend:
    #Dockerfile의 경로
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

      
    # 연결할 외부 디렉토리 : 컨테이너 내 디렉토리(작업공간 app으로 설정해줌 -> frontend/Dockerfile)
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
    - .:/user/src/gz-salon


  db:    # 서비스명 
    image: mysql:8.0.29
    ports:  
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=UTF8
      - --collation-server=utf8_general_ci
    restart: always
    
volumes : 
  mysql_data:


