version: '3'

services:
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

      
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
    - .:/user/src/gz-salon


#  ai:
#    build: ./ai_model
#    image: continuumio/miniconda3
#    ports:
#      - "8888:8888"
#    volumes:
#      - ai_data:/var/lib/ai
#    stdin_open: true
#    tty: true
#

  nginx:
    container_name: "nginx_server"
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
  
 
volumes : 
  mysql_data:
  ai_data:


