version: '3'

services:
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

      
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
    - .:/user/src/gz-salon


  ai:
    build: ./ai_model
    image: continuumio/miniconda3
    ports: 
      - "8888:8888"
    volumes:
      - ai_data:/var/lib/ai
    stdin_open: true
    tty: true
    

  db:    
    image: mysql:8.0.29
    ports:  
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"  
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    command: 
      - --character-set-server=UTF8
    restart: always
  
 
volumes : 
  mysql_data:
  ai_data:


