version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/user/src/gz-salon

  frontend:
    #Dockerfile의 경로
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app